/* This file was generated by SableCC (http://www.sablecc.org/). */

package golite.node;

import golite.analysis.*;

@SuppressWarnings("nls")
public final class AIfStmt extends PStmt
{
    private PExp _exp_;
    private PStmt _block_;
    private PStmt _end_;

    public AIfStmt()
    {
        // Constructor
    }

    public AIfStmt(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") PStmt _block_,
        @SuppressWarnings("hiding") PStmt _end_)
    {
        // Constructor
        setExp(_exp_);

        setBlock(_block_);

        setEnd(_end_);

    }

    @Override
    public Object clone()
    {
        return new AIfStmt(
            cloneNode(this._exp_),
            cloneNode(this._block_),
            cloneNode(this._end_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfStmt(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PStmt getBlock()
    {
        return this._block_;
    }

    public void setBlock(PStmt node)
    {
        if(this._block_ != null)
        {
            this._block_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._block_ = node;
    }

    public PStmt getEnd()
    {
        return this._end_;
    }

    public void setEnd(PStmt node)
    {
        if(this._end_ != null)
        {
            this._end_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._end_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._block_)
            + toString(this._end_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._block_ == child)
        {
            this._block_ = null;
            return;
        }

        if(this._end_ == child)
        {
            this._end_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._block_ == oldChild)
        {
            setBlock((PStmt) newChild);
            return;
        }

        if(this._end_ == oldChild)
        {
            setEnd((PStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
