/* This file was generated by SableCC (http://www.sablecc.org/). */

package golite.node;

import golite.analysis.*;

@SuppressWarnings("nls")
public final class TAmpersandCaretEquals extends Token
{
    public TAmpersandCaretEquals()
    {
        super.setText("&^=");
    }

    public TAmpersandCaretEquals(int line, int pos)
    {
        super.setText("&^=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAmpersandCaretEquals(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAmpersandCaretEquals(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAmpersandCaretEquals text.");
    }
}
