/* This file was generated by SableCC (http://www.sablecc.org/). */

package golite.node;

import golite.analysis.*;

@SuppressWarnings("nls")
public final class TAmpersandCaret extends Token
{
    public TAmpersandCaret()
    {
        super.setText("&^");
    }

    public TAmpersandCaret(int line, int pos)
    {
        super.setText("&^");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAmpersandCaret(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAmpersandCaret(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAmpersandCaret text.");
    }
}
