/* This file was generated by SableCC (http://www.sablecc.org/). */

package golite.node;

import golite.analysis.*;

@SuppressWarnings("nls")
public final class TPipeEquals extends Token
{
    public TPipeEquals()
    {
        super.setText("|=");
    }

    public TPipeEquals(int line, int pos)
    {
        super.setText("|=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPipeEquals(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPipeEquals(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPipeEquals text.");
    }
}
