/* This file was generated by SableCC (http://www.sablecc.org/). */

package golite.node;

import golite.analysis.*;

@SuppressWarnings("nls")
public final class TShiftLeftEquals extends Token
{
    public TShiftLeftEquals()
    {
        super.setText("<<=");
    }

    public TShiftLeftEquals(int line, int pos)
    {
        super.setText("<<=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TShiftLeftEquals(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTShiftLeftEquals(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TShiftLeftEquals text.");
    }
}
