/* This file was generated by SableCC (http://www.sablecc.org/). */

package golite.node;

import golite.analysis.*;

@SuppressWarnings("nls")
public final class TSlashEquals extends Token
{
    public TSlashEquals()
    {
        super.setText("/=");
    }

    public TSlashEquals(int line, int pos)
    {
        super.setText("/=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSlashEquals(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSlashEquals(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSlashEquals text.");
    }
}
