/* This file was generated by SableCC (http://www.sablecc.org/). */

package golite.analysis;

import golite.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAProgram(AProgram node);
    void caseAVarDecl(AVarDecl node);
    void caseAReadStmt(AReadStmt node);
    void caseAPrintStmt(APrintStmt node);
    void caseAAssignStmt(AAssignStmt node);
    void caseAWhileStmt(AWhileStmt node);
    void caseAIfStmt(AIfStmt node);
    void caseAElseStmt(AElseStmt node);
    void caseAEmptyStmt(AEmptyStmt node);
    void caseAPlusExp(APlusExp node);
    void caseAMinusExp(AMinusExp node);
    void caseAMultExp(AMultExp node);
    void caseADivideExp(ADivideExp node);
    void caseAUminusExp(AUminusExp node);
    void caseAIdExp(AIdExp node);
    void caseAFloatExp(AFloatExp node);
    void caseAIntExp(AIntExp node);
    void caseAStringExp(AStringExp node);

    void caseTWhitespace(TWhitespace node);
    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTStar(TStar node);
    void caseTSlash(TSlash node);
    void caseTSemicolon(TSemicolon node);
    void caseTLParen(TLParen node);
    void caseTRParen(TRParen node);
    void caseTEquals(TEquals node);
    void caseTColon(TColon node);
    void caseTVar(TVar node);
    void caseTRead(TRead node);
    void caseTPrint(TPrint node);
    void caseTWhile(TWhile node);
    void caseTDo(TDo node);
    void caseTDone(TDone node);
    void caseTIf(TIf node);
    void caseTThen(TThen node);
    void caseTElse(TElse node);
    void caseTEndif(TEndif node);
    void caseTComment(TComment node);
    void caseTType(TType node);
    void caseTId(TId node);
    void caseTInt(TInt node);
    void caseTFloat(TFloat node);
    void caseTString(TString node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
